### PR TITLE
Issue #6 - Fix of hard-coded serviceID

### PR DESCRIPTION
**Pull request by bertocco**

### CODE REVIEW

**Comment by bertocco** [comment]
Better database portability is achieved removing the schema usage. The schema support can be obtained suitably configuring the deployment file descriptor web.xml. Example:

Whitout schema support:

   <servlet>
     <servlet-name>ProxyServlet</servlet-name>
     <servlet-class>ca.nrc.cadc.cred.server.ProxyServlet</servlet-class>
     <init-param>
        <param-name>trustedPrincipals</param-name>
           <param-value>
             CN=.......DC=...
        </param-value>
     </init-param>
     <init-param>
        <param-name>datasource</param-name>
        <param-value>jdbc/DATABASENAME</param-value>
     </init-param>
     <init-param>
         <param-name>catalog</param-name>
         <param-value>DATABASENAME</param-value>
     </init-param>
     
     <load-on-startup>2</load-on-startup>
   </servlet>

With schema support:

   <servlet>
     <servlet-name>ProxyServlet</servlet-name>
     <servlet-class>ca.nrc.cadc.cred.server.ProxyServlet</servlet-class>
     <init-param>
        <param-name>trustedPrincipals</param-name>
           <param-value>
             CN=.......DC=...
        </param-value>
     </init-param>
     <init-param>
        <param-name>datasource</param-name>
        <param-value>jdbc/DATABASENAME</param-value>
     </init-param>
     <init-param>
         <param-name>catalog</param-name>
         <param-value>DATABASENAME.SCHEMA</param-value>
     </init-param>
     
     <load-on-startup>2</load-on-startup>
   </servlet>

**Comment by bertocco** [comment]
unfortunately github eat xml formatting :(
I try to format correctly:

Without schema support (ex. mysql)

``` xml
   <servlet>
     <servlet-name>ProxyServlet</servlet-name>
     <servlet-class>ca.nrc.cadc.cred.server.ProxyServlet</servlet-class>
     <init-param>
        <param-name>trustedPrincipals</param-name>
        <param-value>
             CN=..........
        </param-value>
     </init-param>
     <init-param>
        <param-name>datasource</param-name>
        <param-value>jdbc/DB_NAME</param-value>
     </init-param>
     <init-param>
         <param-name>catalog</param-name>
         <param-value>DB_NAME</param-value>
     </init-param>
     </servlet>
```

With schema support (ex. mysql)

``` xml
   <servlet>
     <servlet-name>ProxyServlet</servlet-name>
     <servlet-class>ca.nrc.cadc.cred.server.ProxyServlet</servlet-class>
     <init-param>
        <param-name>trustedPrincipals</param-name>
        <param-value>
             CN=..........
        </param-value>
     </init-param>
     <init-param>
        <param-name>datasource</param-name>
        <param-value>jdbc/DB_NAME</param-value>
     </init-param>
     <init-param>
         <param-name>catalog</param-name>
         <param-value>DB_NAME.SCHEMA</param-value>
     </init-param>
     </servlet>
```

**Review by pdowler — COMMENTED** [review]
Unfortunately, the current work (remove hard-coded service identifiers) has become entangled with the previous pull request (cadc-cdp-server changes) because github pull requests are dynamic : they are the current diff between the two repos/branches... and I had not been able to find time to review and resolve the previous one.

And now I see an issue with the previous one: The DelegationsImpl class should not be in the open source code - it belongs in your internal web service project. Looking more closely, it contains a lot of common code that should be pushed up to the open source code (ie the division between Delegations and DelegationsImpl leaves too much common code in the impl) but that is a problem the original development by CADC created and did not resolve properly. 

So: the first thing to do is probably kill this pull request and try to separate the service id fixes so we can finish up with those. It would be great if you can do that part.

At the same time, I will look at the CertificateDAO and DelegationsImpl and sort out a better way for service implementers to customise.

**Comment by bertocco** [comment]
Hi,
please could you review all the proposed changes and let me know what is acceptable for you? This way I'll know what to add to a new pull request.
Points to check in addition to "Issue #6 - Fix of hard-coded serviceID" and "DelegationIml.java addition":
better database portability
Fix issue #8: TERENA certificate support to be fixed

**Pull request closed without merging**
